package spaeher:core;

interface logging {
    log-info: func(value: string);
    log-err: func(value: string);
}

interface plugin-media-provider-records {
    record root-folder {
        id: string,
        path: string,
        duration: u32,
        created-unix:  u64
    }
    record folder {
        id: string,
        name: string,
        root-folder-id: string,
        relative-path: string,
        relative-depth: u32,
        duration: u32,
        indexed-unix: u64
    }
    record file {
        id: string,
        name: string,
        root-folder-id: string,
        relative-path: string,
        relative-depth: u32,
        duration:  u32,
        indexed-unix: u64
    }
    variant error {
        not-implemented,
        path-does-not-exist(string),
        root-folder-does-not-exist(string),
        file-does-not-exist(string),
        folder-does-not-exist(string)
    }
}

interface plugin-transcriber-records {

}

interface plugin-app-records {
    
}