package spaeher:core;

interface logging {
    log-info: func(value: string);
    log-err: func(value: string);
}

interface jobs {
    record job-progress {
        id: string,
        value: f32,
        total-children: option<u32>,
        finished-children: option<u32>
    }
}